[package]
name = "rust-icp"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-kdtree = {path = "../rust-kdtree"}
nalgebra = "0.30.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
rand = "*"
